version: "3.9"
services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ../backend/pet-project-api-gateway/
      dockerfile: Dockerfile
    restart: always
    networks:
      - ${NETWORK_NAME}
    ports:
      - ${API_GATEWAY_PORT}
  chat-service:
    container_name: chat-service
    build:
      context: ../backend/pet-project-chat/
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - redis
    restart: always
    networks:
      - ${NETWORK_NAME}
    ports:
      - ${CHAT_SERVICE_PORT}
  finder-service:
    container_name: finder-service
    build:
      context: ../backend/pet-project-pet-finder/
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - redis
    restart: always
    networks:
      - ${NETWORK_NAME}
    ports:
      - ${FINDER_SERVICE_PORT}
  profile-service:
    container_name: profile-service
    build:
      context: ../backend/pet-project-profile/
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - redis
    restart: always
    networks:
      - ${NETWORK_NAME}
    ports:
      - ${PROFILE_SERVICE_PORT}
  redis:
    container_name: redis
    image: ${REDIS_IMAGE}
    restart: always
    networks:
      - ${NETWORK_NAME}
    ports:
      - ${REDIS_PORT}
    volumes:
      - ${REDIS_VOLUME}:/data
  redis-commander:
    container_name: redis-commander
    image: ${REDIS_COMMANDER_IMAGE}
    depends_on:
      - redis
    restart: always
    networks:
      - ${NETWORK_NAME}
    ports:
      - ${REDIS_COMMANDER_PORT}
  mongodb:
    container_name: mongodb
    image: ${MONGO_IMAGE}
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    networks:
      - ${NETWORK_NAME}
    ports:
      - ${MONGO_PORT}
    volumes:
      - ${MONGO_VOLUME}:/var/lib/mongo
  mongo-express:
    container_name: mongo-express
    image: ${MONGO_EXPRESS_IMAGE}
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL: ${ME_URL}
    networks:
      - ${NETWORK_NAME}
    ports:
      - ${ME_PORT}

networks:
  pet-network:
    name: ${NETWORK_NAME}
